### ISSUE TITLE
Missing data?

### ISSUE THREAD

**Issue by stuartlynn** [tsdataclinic/newerhoods#13]
There seems to be a number of areas that have data that is missing where there shouldn't be. Just checking to make sure that nothing is missing in the data pipeline? Are these just areas with a lack of residential housing?

![Missing data](https://user-images.githubusercontent.com/209838/56908416-418cae00-6a74-11e9-8ee9-8a2ed1bb7dbf.png)

**Comment by kaushik12** [comment]
The basic structure is in place to use either the full set of tracts or ones excluding those with population less than 500. Need to integrate this into the process better with flags for each feature/data and an option for the user to select when uploading their own.

**Comment by kaushik12** [comment]
Modified the population-based exclusion of tracts to a density-based threshold. So, only large public parks and facilities like airports are excluded from the clustering. 8c865fe541636f9319735c55d8f7957ea03b20ce
