### ISSUE TITLE
Download results as PNG for heatmap

### ISSUE THREAD

**Issue by kaushik12** [tsdataclinic/newerhoods#34]
Currently, when you download results as a PNG, you get just the cluster map. We might want to provide both cluster and heat map as individual files or zipped together? Or respond with the file based on their selected view (might be easier and more logical thing to do)

**Comment by corgimli** [comment]
Another option would be to create a composite plot with both maps in one PNG file.

**Comment by kaushik12** [comment]
Yeah, I'm thinking about having a report be downloaded as an option. One that will have both maps, some cluster statistics, Correlation or overlap with different administrative boundaries to name a few.
